### ISSUE TITLE
Customitem and permissions

### ISSUE THREAD

**Issue by Artakia** [AnomalyTea/Horse-Inspector#3]
Hey :)
I would love if you could add a permission for the plugin, so I can give certain players the permission to use it, while others cant.
I'd also like if you could define a custom-item as "item" in the config...so for example I could write 
&6CustomStick in the config, so the plugin would only work if a player used an item called "Customstick" in golden color.

**Comment by AnomalyTea** [comment]
Both features added with v1.3.0
